[workspace]
authors = ["fredwong488 <67003534+fredwong488@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "Imperial-paper-implementations"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
l-ora = {cmd = "python scripts/run_ora_sweep.py --classes Car Pedestrian Cyclist --difficulties Easy Moderate Hard --metric-types ap pr recall_iou --budgets 0 10 20 40 60 100 150 200"}
l-ora-vr = {cmd = "python scripts/run_sweep.py --attack ora --attack-fraction 0.5 --defense void_region --detector pointrcnn --classes Car Pedestrian Cyclist --difficulties Easy Moderate Hard --metric-types ap pr recall_iou detection_rate --sweep-param budget --sweep-values 0 10 20 40 60 100 150 200"}
s-ora = {cmd = "python scripts/run_ora_sweep.py --num-frames 50 --classes Car Pedestrian Cyclist --difficulties Easy Moderate Hard --metric-types ap pr recall_iou --budgets 0 10 20 40 60 100 150 200"}
s-ora-vr = {cmd = "python scripts/run_sweep.py --attack ora --attack-fraction 0.5 --defense void_region --detector pointrcnn --num-frames 50 --classes Car Pedestrian Cyclist --difficulties Easy Moderate Hard --metric-types ap pr recall_iou detection_rate --sweep-param budget --sweep-values 0 10 20 40 60 100 150 200"}
s-ora-vr-min-samples = {cmd = "python scripts/run_sweep.py --attack ora --attack-fraction 0.5 --defense void_region --detector pointrcnn --num-frames 50 --metric-types detection_rate --sweep-target defense --sweep-param obstacle_dbscan_min_samples --sweep-values 10 25 50 75 100 150 200"}
s-ora-vr-min-frustum = {cmd = "python scripts/run_sweep.py --attack ora --attack-fraction 0.5 --defense void_region --detector pointrcnn --num-frames 50 --metric-types detection_rate --sweep-target defense --sweep-param min_frustum_points --sweep-values 0 1 3 5 10 20"}
t-ora = {cmd = "python scripts/run_ora_sweep.py --num-frames 50 --classes Car Pedestrian Cyclist --difficulties Easy Moderate Hard --metric-types ap pr recall_iou --budgets 0 40 100 200"}
tmux-create = {cmd = "tmux new-session -s"}
tmux-reattach = {cmd = "tmux attach -t"}
fm = {cmd = "python tools/format_metrics.py"}
vm = {cmd = "python tools/visualise_metrics.py"}

[system-requirements]
cuda = "11.8"

[dependencies]
python = ">=3.11.0,<3.12"
numpy = ">2"
matplotlib = "*"
joblib = "*"
scikit-learn = "*"
discretize = "*"
ipykernel = "*"
llvm-openmp = "*"
open3d = "*"  
shapely = "*"
llvmlite = "*"
numba = "*"
tensorboardx = "*"
easydict = "*"
pyyaml = "*"
scikit-image = "*"
tqdm = "*"
opencv = "*"
pip = "*"

[target.linux-64.dependencies]


[target.osx-arm64.pypi-dependencies]
torch = "*"
torchvision = "*"

[target.linux-64.pypi-dependencies]
torch = { version = ">=2", index = "https://download.pytorch.org/whl/cu118" }
torchvision = { index = "https://download.pytorch.org/whl/cu118" }
spconv-cu118 = "*"
SharedArray = "*"
pyquaternion = "*"
